### ISSUE TITLE
Keep track of all projects using lutaml-model

### ISSUE THREAD

**Issue by ronaldtse** [lutaml/lutaml-model#105]
Using:
* https://github.com/lutaml/genericode
* https://github.com/lutaml/ogc-gml
* https://github.com/metanorma/modspec-ruby
* https://github.com/metanorma/rfcxml
* https://github.com/metanorma/niso-jats
* https://github.com/metanorma/sts-ruby
* https://github.com/lutaml/metaschema
* https://github.com/glossarist/termium
* https://github.com/lutaml/oasis-etm
* https://github.com/lutaml/ali
* https://github.com/lutaml/reqif

In migration:
* https://github.com/lutaml/xmi/pull/49
* https://github.com/lutaml/oscal/issues/18
* https://github.com/plurimath/mml/pull/2
* https://github.com/metanorma/metanorma/pull/403

Pending migration:
* https://github.com/plurimath/omml
* https://github.com/glossarist/glossarist-ruby/issues/107

**Comment by ronaldtse** [comment]
@HassanAkbar this is so that we know what gems we can test against to know if the latest versions of lutaml-model are backwards compatible (i.e. will any user break).

**Comment by ronaldtse** [comment]
@CAMOBAP a recent update of lutaml-model broke some of the gems. We wish to add an automated workflow that runs the tests of some external gems that we manage, such as:

simple ones:
* ogc-gml
* genericode

complex ones:
* sts-ruby
* xmi

Can we make those part of the build process (as separate jobs)? i.e. we checkout those repositories, run their specs against our local code of lutaml-model.

**Comment by opoudjis** [comment]
This will eventually include metanorma and modspec-ruby. But not until the integration issues for them are debugged and confirmed.

**Comment by CAMOBAP** [comment]
For now, we have two approaches for testing which are 'flavor'-based in `relaton-index` and `pubid-core`:
- https://github.com/relaton/relaton-index/blob/main/.github/workflows/dependent-tests.yml
- https://github.com/metanorma/pubid-core/blob/main/.github/workflows/dependent-tests.yml

It makes sense to make a more general approach to list repo name instead flavor and reuse it in this repo + `relaton-index`, `pubid-core` too

**Comment by CAMOBAP** [comment]
Done https://github.com/lutaml/lutaml-model/actions/runs/12109210193/job/33758076323

Some repos failed

**Comment by ronaldtse** [comment]
Thank you @CAMOBAP !
