### ISSUE TITLE
One caveat of the Nokogiri adapter

### ISSUE THREAD

**Issue by Novtopro** [lutaml/lutaml-model#127]
I observed a caveat in the Nokogiri adapter.

![CleanShot 2024-10-29 at 10 41 25@2x](https://github.com/user-attachments/assets/a74eefe8-cf2d-4239-a6e2-bb43de4fec7f)

For example, I want to add a `<comment>` tag instead of adding a comment in the XML, but when I send the `comment` message to the builder, it will invoke the `comment` method of the `Nokogiri::XML::Builder` which in turn adds a comment in the XML instead of adding a tag

![CleanShot 2024-10-29 at 10 43 32@2x](https://github.com/user-attachments/assets/6cbe8d6d-26c0-466b-9975-70f02546a1ec)

As a simple solution, we can just check if the `Nokogiri::XML::Builder` responds to the message represented by the tag_name, if it does, we rewrite the message by adding an underscore to the end.

**Comment by ronaldtse** [comment]
@Novtopro thank you for this, because this is clearly a bug in lutaml-model. Will review.

**Comment by opoudjis** [comment]
A similar issue happened with p as a tag recently.
