### ISSUE TITLE
Handle `import` tags in schema

### ISSUE THREAD

**Issue by suleman-uzair** [lutaml/lutaml-model#181]
Handle `imports` in XSD schemas.

_Originally posted by @ronaldtse in https://github.com/lutaml/lutaml-xsd/pull/2#pullrequestreview-2444077416_

**Comment by suleman-uzair** [comment]
@ronaldtse, do you have any thoughts on how to handle the imports?
1. Import the schemas recursively?
   a. Import the schema or document from the input. If any imports exist within that schema or document, continue importing recursively.
3. Handle like shale does, as discussed in https://github.com/lutaml/lutaml-model/issues/37#issuecomment-2401640642

**Comment by ronaldtse** [comment]
I think the xsd gem should have a functionality called "flatten" that unrolls the imports. Then the lutaml-model gem can directly import that XSD just once?

**Comment by suleman-uzair** [comment]
> I think the xsd gem should have a functionality called “flatten” that unrolls the imports. Then the lutaml-model gem can directly import that XSD just once?

@ronadltse, Sounds good.
I’ll start working on it right away and move back to XSD compiling functionality ( in Lutaml-Model ) once it’s finalized.
