### ISSUE TITLE
Fix specs

### ISSUE THREAD

**Issue by ronaldtse** [lutaml/lutaml-model#2]
75 spec failures right now.

There are a number of specs, and as you can see, some basic features work, but many are not completed (collections, `map_content`). Once we have the specs fixed it should be close to be ready to use. Then it will be a cycle of iterative improvements.

@HassanAkbar can you please help here?

**Comment by HassanAkbar** [comment]
@ronaldtse Sure, I'll fix the test cases.

**Comment by ronaldtse** [comment]
This is done, thanks @HassanAkbar !
