### ISSUE TITLE
Using custom model

### ISSUE THREAD

**Issue by andrew2net** [lutaml/lutaml-model#25]
Shale has a `model` [directive](https://www.shalerb.org/#using-custom-models) which allows to use a custom model class. In the lutaml-model the directive doesn't work. How can we use custom classes with this gem?

**Comment by HassanAkbar** [comment]
@andrew2net Currently I'm working on adding this feature to `lutaml-model`. This will be available in few days.

**Comment by andrew2net** [comment]
Thank you @HassanAkbar. Please let me know when it's available.
