### ISSUE TITLE
(URGENT) Change custom serialization methods to adopt Shale API

### ISSUE THREAD

**Issue by ronaldtse** [lutaml/lutaml-model#51]
There is an implementation difference between Lutaml::Model and Shale for custom serialization methods.

What should we do?

Preliminary thoughts:
1. The `*_to_{format}` methods are for "serialization of a value", i.e. model to JSON/XML. There are a few reasons why users want to do this:
    * Simple transformation of value. When the serialization format is correct. Writing out the value in the proper location of the serialization format based on the value itself.
    * Aggregating multiple model values into one. Perhaps the target value is an aggregated value.
    * Writing the value at a different or multiple locations in the serialized structure. Involves manually creating XML elements etc.
2. The `*_from_{format}` methods are for "deserialization of a value" from the serialization format. There are again multiple reasons of using this:
    * Simple transformation of value. Reading the value from the proper location of the serialization format, and then writing it to the model value.
    * Splitting values. Reading a value from the proper location and assigning parts of the value to different model attributes.
    * Consolidating values. Reading values from multiple locations and processing them into one model attribute.

How should we support these cases?

Custom serialization methods in `Lutaml::Model` map to individual attributes.

For custom serialization methods, Lutaml::Model uses the `:with` keyword
instead of the `:using` keyword used by Shale.

```ruby
class Example < Lutaml::Model::Serializable
  attribute :name, :string
  attribute :size, :integer
  attribute :color, :string
  attribute :description, :string

  json do
    map "name", to: :name, with: { to: :name_to_json, from: :name_from_json }
    map "size", to: :size
    map "color", to: :color,
                 with: { to: :color_to_json, from: :color_from_json }
    map "description", to: :description,
                       with: { to: :description_to_json, from: :description_from_json }
  end

  xml do
    root "CustomSerialization"
    map_element "Name", to: :name,
                        with: { to: :name_to_xml, from: :name_from_xml }
    map_attribute "Size", to: :size
    map_element "Color", to: :color,
                         with: { to: :color_to_xml, from: :color_from_xml }
    map_content to: :description,
                with: { to: :description_to_xml,
                        from: :description_from_xml }
  end

  def name_to_json(_model, value)
    "JSON Masterpiece: #{value}"
  end

  def name_from_json(_model, doc)
    doc["name"].sub(/^JSON Masterpiece: /, "")
  end

  def color_to_json(_model, value)
    value.upcase
  end

  def color_from_json(_model, doc)
    doc["color"].downcase
  end

  def description_to_json(_model, value)
    "JSON Description: #{value}"
  end

  def description_from_json(_model, doc)
    doc["description"].sub(/^JSON Description: /, "")
  end

  def name_to_xml(_model, value)
    "XML Masterpiece: #{value}"
  end

  def name_from_xml(_model, value)
    value.sub(/^XML Masterpiece: /, "")
  end

  def color_to_xml(_model, value)
    value.upcase
  end

  def color_from_xml(_model, value)
    value.downcase
  end

  def description_to_xml(_model, value)
    "XML Description: #{value}"
  end

  def description_from_xml(_model, value)
    value.sub(/^XML Description: /, "")
  end
end
```

Custom serialization methods in Shale do not map to specific attributes, but
allow the user to specify where the data goes.

```ruby
class Example < Shale::Mapper
  attribute :name, Shale::Type::String
  attribute :size, Shale::Type::Integer
  attribute :color, Shale::Type::String
  attribute :description, Shale::Type::String

  json do
    map "name", using: { from: :name_from_json, to: :name_to_json }
    map "size", to: :size
    map "color", using: { from: :color_from_json, to: :color_to_json }
    map "description", to: :description, using: { from: :description_from_json, to: :description_to_json }
  end

  xml do
    root "CustomSerialization"
    map_element "Name", using: { from: :name_from_xml, to: :name_to_xml }
    map_attribute "Size", to: :size
    map_element "Color", using: { from: :color_from_xml, to: :color_to_xml }
    map_content to: :description, using: { from: :description_from_xml, to: :description_to_xml }
  end

  def name_to_json(model, doc)
    doc['name'] = "JSON Masterpiece: #{model.name}"
  end

  def name_from_json(model, value)
    model.name = value.sub(/^JSON Masterpiece: /, "")
  end

  def color_to_json(model, doc)
    doc['color'] = model.color.upcase
  end

  def color_from_json(model, doc)
    model.color = doc['color'].downcase
  end

  def description_to_json(model, doc)
    doc['description'] = "JSON Description: #{model.description}"
  end

  def description_from_json(model, doc)
    model.description = doc['description'].sub(/^JSON Description: /, "")
  end

  def name_from_xml(model, node)
    model.name = node.text.sub(/^XML Masterpiece: /, "")
  end

  def name_to_xml(model, parent, doc)
    name_element = doc.create_element('Name')
    doc.add_text(name_element, model.street.to_s)
    doc.add_element(parent, name_element)
  end
end
```

**Comment by HassanAkbar** [comment]
@ronaldtse For `*_to_{format}` the shale gem process by generating an empty model object and filling it with information while we are processing it by generating a hash first and then generating the model using that hash. 

To allow the above change in `lutaml-model` we will need to change the flow a little to match with shale.

**Comment by HassanAkbar** [comment]
> The best solution for us is actually to adopt the Shale API for custom methods, and then differentiate later.

@ronaldtse Sure, I'll update the `lutaml-model` to use the same API

**Comment by ronaldtse** [comment]
@HassanAkbar actually going from:
* JSON => Hash => Object
* Object => Hash => JSON

Are both rather cumbersome to the user unless the API is properly described.

The Shale custom method APIs are not well documented but they do provide example code. For example, the XML custom methods describe using `add_element` and other XML specific methods to work with an XML document, but these methods are not described.

In our case, we need to document the API to be used inside serialization custom methods.

**Comment by ronaldtse** [comment]
Is this done in #56?

**Comment by HassanAkbar** [comment]
@ronaldtse Yes this is done in #56. Now Shale and Lutaml::Model follows the same API for custom methods

**Comment by ronaldtse** [comment]
Thanks @HassanAkbar ! let’s close this then.
