### ISSUE TITLE
(URGENT) undefined method `item_order' for an instance of String

### ISSUE THREAD

**Issue by ronaldtse** [lutaml/lutaml-model#59]
From a number of migrations:

* https://github.com/lutaml/ogc-gml/pull/7
* https://github.com/lutaml/genericode/pull/13

We encounter errors like these:

```
  1) Ogc::Gml::Curve round-trips Curve-ArcByCenterPoint.xml
     Failure/Error:
       output = Ogc::Gml::Curve.from_xml(input).to_xml(
         pretty: true,
         declaration: true,
         encoding: "utf-8"
       )
     
     NoMethodError:
       undefined method `item_order' for an instance of String
     # ./spec/ogc/gml/curve_spec.rb:23:in `block (3 levels) in <top (required)>'
```

The `item_order` issue is a problem encountered in a number of migrations including in:
* https://github.com/lutaml/xmi/issues/45

I think the ogc-gml gem is the simplest place to reproduce and fix this because it does not utilize any advanced features of lutaml-model such as "model" or "custom methods".

**Comment by kwkwan** [comment]
Similar error when migrate xmi to use lutaml-model https://github.com/lutaml/xmi/issues/46

**Comment by HassanAkbar** [comment]
@ronaldtse The issue has been fixed and also verified in the linked repos. 
Is there something else left to be done in the context of this ticket? or should I close this?

**Comment by ronaldtse** [comment]
Let’s close it. Thanks!
