### ISSUE TITLE
Fix custom methods example in doc

### ISSUE THREAD

**Issue by andrew2net** [lutaml/lutaml-model#66]
In the doc's [Attribute serialization with custom methods](https://github.com/lutaml/lutaml-model#attribute-serialization-with-custom-methods) section there is an example:
```ruby
...
  def name_to_json(model, value)
    doc["name"] = "Masterpiece: #{value}"
  end

  def name_from_json(model, doc)
    model.name = value.sub(/^JSON Masterpiece: /, '')
  end
...
```
The `name_to_json` method uses `doc` but doesn't have such argument. It has `value` but doesn't use.
The `name_from_json` uses `value` but doesn't have that argument. It has `doc` instead.

**Comment by HassanAkbar** [comment]
@andrew2net Thank you for pointing this out. This is a mistake in the documentation and I will fix it ASAP
