### ISSUE TITLE
Cast values to type when assigning to attributes

### ISSUE THREAD

**Issue by HassanAkbar** [lutaml/lutaml-model#79]
Currently when assigning a value to an attribute it does not gets casted to its respective type. What is happening now is

```ruby
class Test
  attribute :file_name, Lutaml::Model::Type::String
end

obj = Test.new
obj.file_name = Pathname.new(file)

puts obj.file_name
# => <Pathname:...> 
```

This is causing failures in https://github.com/metanorma/metanorma/pull/403 because it is not getting casted to string which is the type of the `file_name` attribute.

**Comment by ronaldtse** [comment]
Good find, this is something we must resolve.
