### ISSUE TITLE
Error `to: attribute_name` not found even if custom method is given

### ISSUE THREAD

**Issue by HassanAkbar** [lutaml/lutaml-model#81]
Currently we are raising error even if custom methods are provided for serialization which do not require the attribute. So we should check only one condition, either `to:` or `with:` needs to be present at a time, if both are given `with:` should be used without raising an error.

for https://github.com/metanorma/metanorma/pull/403

**Comment by ronaldtse** [comment]
Then maybe we do not allow the "to" when "with" is set. This brings us in alignment with Shale.

**Comment by HassanAkbar** [comment]
@ronaldtse Got it, will add validation in alignment with Shale.
