### ISSUE TITLE
serialisation must not force validation

### ISSUE THREAD

**Issue by opoudjis** [lutaml/lutaml-model#82]
From https://github.com/metanorma/modspec-ruby/issues/9

modspec-ruby is making assumptions about what counts as a valid requirement object, which may be valid for an integrated suite of YAML files. Those conditions cannot be satisfied while I am processing requirements in isolation on parsing a Metanorma document. And the premise that I cannot even serialise an object, to do further processing, without it being validated, is a premise I reject. 

lib/lutaml/model/serialize.rb is forcing validation: 

````
Lutaml::Model::Config::AVAILABLE_FORMATS.each do |format|
        define_method(:"to_#{format}") do |options = {}|
          validate!
          adapter = Lutaml::Model::Config.public_send(:"#{format}_adapter")
          representation = if format == :xml
                             self
                           else
                             self.class.hash_representation(self, format,
                                                            options)
                           end
            
          adapter.new(representation).public_send(:"to_#{format}", options)
        end            
      end            
````

I need that `validate!` to be made optional: in the context of Metanorma, which does heavy postprocessing, and which processes bits of data in isolation, forced validation is not acceptable, and it is currently preventing further work on integrating modspec-ruby. I suggest using `.to_xml(valid: false)` to make that validation optional.

**Comment by ronaldtse** [comment]
Thanks @opoudjis for raising this. 

There is a behavioral preference issue here I don't fully know. 

1. Should validation occur on serialization? I think the answer as you said is no. Only a manual call should validate. 
2. Should validation be an option on the object? If no one calls "validate" or "validate!" manually, then there won't be any errors raised, ie. There is no need to set "validate or not" as an option to persist with the object. 

Is this accurate?
